# Generated by Django 4.1.3 on 2023-01-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('type', models.CharField(max_length=100)),
                ('beds', models.PositiveIntegerField(blank=True, null=True)),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('area_type', models.CharField(choices=[('NIA', 'NIA'), ('NSA', 'NSA')], max_length=3)),
                ('area_metric', models.CharField(choices=[('SQFT', 'square feet'), ('SQM', 'square metres')], max_length=4)),
                ('asset_class', models.CharField(choices=[('BTS', 'Build to Sell'), ('BTL', 'Build to Let'), ('H', 'Hotel'), ('C', 'Commercial'), ('O', 'Office'), ('S', 'Shopping Centre'), ('PBSA', 'Student Accommodation')], max_length=10)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='loan.scheme')),
            ],
        ),
    ]
