# Generated by Django 4.1.3 on 2023-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='area_metric',
            field=models.CharField(blank=True, choices=[('SQFT', 'square feet'), ('SQM', 'square metres')], max_length=4),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area_type',
            field=models.CharField(blank=True, choices=[('NIA', 'NIA'), ('NSA', 'NSA')], max_length=3),
        ),
    ]
