# Generated by Django 4.1.3 on 2023-01-03 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_borrower'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.borrower'),
        ),
    ]
