# Generated by Django 4.1.3 on 2023-01-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0003_alter_unit_area_metric_alter_unit_area_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='currency',
            field=models.CharField(choices=[('GBP', '£'), ('EUR', '€'), ('USD', '$')], default='GBP', max_length=3),
        ),
        migrations.AddField(
            model_name='scheme',
            name='system',
            field=models.CharField(choices=[('SQFT', 'imperial (sqft)'), ('SQM', 'metric (sqm)')], default='SQFT', max_length=4),
        ),
    ]
