# Generated by Django 4.1.3 on 2023-01-31 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0004_scheme_currency_scheme_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='area_metric',
        ),
    ]
