# Generated by Django 4.1.3 on 2023-02-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_remove_unit_area_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='currency',
            field=models.CharField(choices=[('GBP', 'GBP (£)'), ('EUR', 'EUR (€)'), ('USD', 'USD ($)')], default='GBP', max_length=3),
        ),
    ]
