# Generated by Django 4.1.3 on 2023-02-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_scheme_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='area_type',
            field=models.CharField(blank=True, choices=[('NIA', 'Net Internal Area'), ('NSA', 'Net Salable Area'), ('GIA', 'Gross Internal Area')], max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='asset_class',
            field=models.CharField(choices=[('BTS', 'Residential - Build to Sell'), ('BTL', 'Residential - Build to Let'), ('H', 'Hotel'), ('C', 'Commercial'), ('O', 'Office'), ('S', 'Shopping Centre'), ('PBSA', 'Student Accommodation')], max_length=10),
        ),
    ]
