# Generated by Django 4.1.3 on 2023-01-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_scheme_delete_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='street_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
