# Generated by Django 4.1.6 on 2023-02-11 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0008_alter_unit_options_unit_author_unit_author_firm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='type',
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('room', 'room'), ('unit', 'unit')], default='unit', max_length=100),
        ),
        migrations.AddField(
            model_name='unit',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_class_type', models.CharField(choices=[('BTS', 'Residential - Build to Sell'), ('BTL', 'Residential - Build to Let'), ('H', 'Hotel'), ('C', 'Commercial'), ('O', 'Office'), ('S', 'Shopping Centre'), ('PBSA', 'Student Accommodation')], max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.firm')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_classes', to='loan.scheme')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='unit',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='loan.assetclass'),
        ),
    ]
