# Generated by Django 4.1.6 on 2023-02-11 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0009_remove_unit_scheme_remove_unit_type_unit_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='loan.scheme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'unit'), ('room', 'room')], default='unit', max_length=100),
        ),
    ]
