# Generated by Django 4.1.6 on 2023-02-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_unit_scheme_alter_unit_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='value',
        ),
        migrations.AlterField(
            model_name='unit',
            name='asset_class',
            field=models.CharField(choices=[('BTS', 'Residential - Build to Sell'), ('BTL', 'Residential - Build to Let'), ('H', 'Hotel'), ('C', 'Commercial'), ('O', 'Office'), ('S', 'Shopping Centre'), ('PBSA', 'Student Accommodation')], default='BTS', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('room', 'Room')], default='unit', max_length=100),
        ),
        migrations.DeleteModel(
            name='AssetClass',
        ),
    ]
