# Generated by Django 4.1.6 on 2023-02-19 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
        ('loan', '0011_remove_unit_value_alter_unit_asset_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.firm')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='system',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='area',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='beds',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='scheme',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.AddField(
            model_name='scheme',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='identifier',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('assetclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.assetclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('loan.assetclass',),
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('assetclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.assetclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('loan.assetclass',),
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('assetclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.assetclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('loan.assetclass',),
        ),
        migrations.CreateModel(
            name='Retail',
            fields=[
                ('assetclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.assetclass')),
                ('description', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('loan.assetclass',),
        ),
        migrations.CreateModel(
            name='ShoppingCentre',
            fields=[
                ('assetclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.assetclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('loan.assetclass',),
        ),
        migrations.CreateModel(
            name='StudentAccommodation',
            fields=[
                ('assetclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.assetclass')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
            bases=('loan.assetclass',),
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, default='', max_length=100)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('measure', models.CharField(blank=True, choices=[('CM', 'centimetres'), ('IN', 'inches')], max_length=3)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('author_firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.firm')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='loan.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='assetclass',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_asset_classes', to='loan.scheme'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('type', models.CharField(blank=True, choices=[('NIA', 'Net Internal Area'), ('NSA', 'Net Salable Area'), ('GIA', 'Gross Internal Area')], max_length=3)),
                ('system', models.CharField(choices=[('SQFT', 'imperial (sqft)'), ('SQM', 'metric (sqm)')], default='SQFT', max_length=4)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_definitions', to='loan.unit')),
            ],
        ),
        migrations.AlterField(
            model_name='unit',
            name='asset_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='loan.assetclass'),
        ),
    ]
