# Generated by Django 4.1.6 on 2023-02-20 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_assetclass_remove_scheme_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetclass',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_classes', to='loan.scheme'),
        ),
    ]
