# Generated by Django 4.1.6 on 2023-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0013_alter_assetclass_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='label',
            field=models.CharField(blank=True, choices=[('UNIT', 'unit'), ('ROOM', 'room')], max_length=10),
        ),
    ]
