# Generated by Django 4.1.6 on 2023-02-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0014_unit_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='system',
            field=models.CharField(choices=[('SQFT', 'imperial (sqft)'), ('SQM', 'metric (sqm)')], default='SQFT', max_length=4),
        ),
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.CharField(blank=True, choices=[('NIA', 'Net Internal Area'), ('NSA', 'Net Salable Area'), ('GIA', 'Gross Internal Area'), ('GEA', 'Gross External Area')], max_length=3),
        ),
    ]
