# Generated by Django 4.1.6 on 2023-02-26 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_scheme_system_alter_area_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='area_type',
            field=models.CharField(blank=True, choices=[('NIA', 'Net Internal Area'), ('GIA', 'Gross Internal Area')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Area',
        ),
    ]
