# Generated by Django 4.1.6 on 2023-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0016_unit_area_size_unit_area_type_delete_area'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetclass',
            options={'verbose_name_plural': 'Asset Classes'},
        ),
        migrations.AddField(
            model_name='unit',
            name='beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
    ]
