# Generated by Django 4.1.6 on 2023-03-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_alter_assetclass_options_unit_beds_delete_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='label',
            field=models.CharField(blank=True, choices=[('unit', 'unit'), ('room', 'room')], max_length=10),
        ),
    ]
