# Generated by Django 4.1.6 on 2023-03-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0018_alter_unit_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='use',
            field=models.CharField(default='hotel', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.scheme'),
        ),
    ]
