# Generated by Django 4.1.6 on 2023-03-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_assetclass_use_alter_assetclass_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='identifier',
            field=models.CharField(default='1', max_length=10, verbose_name='unit number'),
        ),
    ]
