# Generated by Django 4.1.6 on 2023-03-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0020_alter_unit_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetclass',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_classes', to='loan.scheme'),
        ),
    ]
