# Generated by Django 4.1.6 on 2023-03-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0021_alter_assetclass_scheme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retail',
            name='description',
        ),
    ]
