# Generated by Django 4.1.6 on 2023-03-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0022_remove_retail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True),
        ),
    ]
