# Generated by Django 4.1.6 on 2023-03-16 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0023_alter_unit_area_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['created_at']},
        ),
    ]
