# Generated by Django 4.1.6 on 2023-03-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0024_alter_unit_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='area_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
