# Generated by Django 4.1.6 on 2023-03-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0025_alter_unit_area_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='area_size',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
