# Generated by Django 4.1.6 on 2023-03-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0026_alter_unit_area_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='is_built',
            field=models.BooleanField(default=False),
        ),
    ]
