# Generated by Django 4.1.6 on 2023-03-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0027_scheme_is_built'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retail',
            new_name='Commercial',
        ),
    ]
