# Generated by Django 4.1.6 on 2023-03-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0028_rename_retail_commercial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='investment_strategy',
            field=models.CharField(blank=True, choices=[('build_to_sell', 'build to sell'), ('build_to_rent', 'build to rent')], default='', max_length=100),
        ),
    ]
