# Generated by Django 4.1.6 on 2023-03-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0029_assetclass_investment_strategy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commercial',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='residential',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='shoppingcentre',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='studentaccommodation',
            options={'ordering': ['created_at']},
        ),
    ]
