# Generated by Django 4.1.6 on 2023-03-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0030_alter_commercial_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='value',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=20),
        ),
    ]
