# Generated by Django 4.1.6 on 2023-04-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0032_alter_unit_options_alter_assetclass_scheme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetclass',
            name='investment_strategy',
            field=models.CharField(blank=True, choices=[('build_to_sell', 'build to sell'), ('build_to_rent', 'build to rent')], default='build_to_sell', max_length=100),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('open_market', 'open market'), ('discounted_rental', 'discounted rental')], default='open_market', max_length=100),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'open market'), ('under_offer', 'under offer'), ('exchanged', 'exchanged'), ('completed', 'completed')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='tenant_type',
            field=models.CharField(blank=True, choices=[('private_individual', 'private individual'), ('company', 'company')], default='private_individual', max_length=100),
        ),
        migrations.AlterField(
            model_name='unit',
            name='area_type',
            field=models.CharField(blank=True, choices=[('NIA', 'Net Internal Area'), ('GIA', 'Gross Internal Area')], default='NIA', max_length=3),
        ),
        migrations.AlterField(
            model_name='unit',
            name='label',
            field=models.CharField(blank=True, choices=[('unit', 'unit'), ('room', 'room')], default='unit', max_length=10),
        ),
    ]
