# Generated by Django 4.2 on 2023-04-17 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0034_company_individual_remove_lease_tenant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='author',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='author_firm',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='company_tenant',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='individual_tenant',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='length_days',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='tenant_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='buyer_type',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='company_buyer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='individual_buyer',
        ),
        migrations.AddField(
            model_name='lease',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='buyer',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease', related_query_name='lease', to='loan.unit'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Individual',
        ),
    ]
