# Generated by Django 4.2 on 2023-04-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0036_remove_lease_rent_remove_lease_rent_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='value',
        ),
        migrations.AddField(
            model_name='lease',
            name='duration_unit',
            field=models.CharField(blank=True, choices=[('months', 'month'), ('weeks', 'weeks')], default='months', max_length=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='duration_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
