# Generated by Django 4.2 on 2023-05-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0040_alter_assetclass_investment_strategy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetclass',
            options={'ordering': ['created_at']},
        ),
    ]
