# Generated by Django 4.2 on 2023-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0041_alter_assetclass_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lease',
            old_name='duration_unit',
            new_name='lease_frequency',
        ),
        migrations.RenameField(
            model_name='lease',
            old_name='duration_value',
            new_name='term',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='rent_achieved_amount',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='rent_achieved_frequency',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='rent_target_amount',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='rent_target_frequency',
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_achieved',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'weekly'), ('monthly', 'monthly')], default='weekly', max_length=100),
        ),
        migrations.AddField(
            model_name='lease',
            name='rent_target',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
