# Generated by Django 4.2 on 2023-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0043_alter_lease_rent_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='area_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
