# Generated by Django 4.2 on 2023-05-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0046_alter_lease_options_remove_lease_lease_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('under_offer', 'under offer'), ('exchanged', 'exchanged'), ('completed', 'completed')], max_length=20),
        ),
    ]
