# Generated by Django 4.2 on 2023-05-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0047_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'available'), ('under_offer', 'under offer'), ('exchanged', 'exchanged'), ('completed', 'completed')], default='available', max_length=20),
        ),
    ]
