# Generated by Django 4.2 on 2023-05-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0048_alter_sale_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='identifier',
            field=models.CharField(max_length=10, verbose_name='unit number'),
        ),
    ]
