# Generated by Django 4.2 on 2023-05-21 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0049_alter_unit_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('assetclass_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='loan.assetclass')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
            bases=('loan.assetclass',),
        ),
        migrations.AlterField(
            model_name='assetclass',
            name='use',
            field=models.CharField(choices=[('hotel', 'hotel'), ('residential', 'residential'), ('commercial', 'commercial'), ('student_accommodation', 'student accommodation'), ('office', 'office'), ('shopping_centre', 'shopping centre'), ('parking', 'parking')], default='residential', max_length=40),
        ),
    ]
