# Generated by Django 4.2 on 2023-05-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0050_parking_alter_assetclass_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetclass',
            name='sub_use',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
