# Generated by Django 4.2 on 2023-05-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0051_assetclass_sub_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetclass',
            name='sub_use',
        ),
    ]
