# Generated by Django 4.2 on 2023-05-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0052_remove_assetclass_sub_use'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='ownership_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
