# Generated by Django 4.2 on 2023-05-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0053_unit_ownership_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='ownership_type',
        ),
        migrations.AddField(
            model_name='sale',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('affordable', 'affordable'), ('private', 'private')], default='private', max_length=20),
        ),
    ]
