# Generated by Django 4.2 on 2023-05-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0054_remove_unit_ownership_type_sale_ownership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('open_market', 'open market'), ('discounted_rental', 'discounted rental')], default='open_market', max_length=100),
        ),
    ]
