# Generated by Django 4.2.1 on 2023-06-03 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0055_lease_lease_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lease',
            name='rent_frequency',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='area_type',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='label',
        ),
        migrations.AlterField(
            model_name='scheme',
            name='system',
            field=models.CharField(choices=[('sqft', 'imperial (sqft)'), ('sqm', 'metric (sqm)')], default='sqft', max_length=4),
        ),
    ]
