# Generated by Django 4.1.3 on 2022-12-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_firm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
