# Generated by Django 4.1.3 on 2022-12-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_firm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='name',
            field=models.CharField(max_length=255, verbose_name='firm name'),
        ),
    ]
